# Generated by Django 4.2.6 on 2023-10-23 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='blog',
            name='appraisal',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='blog',
            name='content',
            field=models.TextField(default='Nothing'),
        ),
        migrations.AddField(
            model_name='blog',
            name='intro',
            field=models.CharField(default='None', max_length=300),
        ),
        migrations.AddField(
            model_name='blog',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.author'),
        ),
    ]
