# Generated by Django 4.2.6 on 2023-10-23 15:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_author_blog_appraisal_blog_content_blog_intro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='blog',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
