# Generated by Django 4.2.6 on 2023-10-25 05:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_author_user_avatar_user_level_alter_blog_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='dob',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='user',
            name='dob',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='user',
            name='join_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='author',
            name='join_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
