# Generated by Django 4.2.6 on 2023-10-25 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_author_join_date_alter_user_join_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='level',
        ),
    ]
