# Generated by Django 4.2.6 on 2023-10-26 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_alter_blog_published_alter_blog_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
