# Generated by Django 4.2.6 on 2023-10-26 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_alter_word_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='blog',
        ),
        migrations.AddField(
            model_name='word',
            name='blog',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='base.blog'),
        ),
    ]
