# Generated by Django 4.2.6 on 2023-10-26 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_word_blog_word_level_word_note_word_synonym_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='image',
            field=models.ImageField(default=None, upload_to='images/'),
        ),
    ]
