# Generated by Django 4.2.6 on 2023-10-26 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_word_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='blog',
        ),
        migrations.RemoveField(
            model_name='word',
            name='definition',
        ),
        migrations.RemoveField(
            model_name='word',
            name='example',
        ),
        migrations.RemoveField(
            model_name='word',
            name='image',
        ),
        migrations.RemoveField(
            model_name='word',
            name='mean',
        ),
        migrations.RemoveField(
            model_name='word',
            name='synonym',
        ),
        migrations.RemoveField(
            model_name='word',
            name='word',
        ),
    ]
