# Generated by Django 4.2.6 on 2023-10-26 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_remove_word_blog_remove_word_definition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='blog',
            field=models.ManyToManyField(related_name='words', to='base.blog'),
        ),
        migrations.AddField(
            model_name='word',
            name='definition',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='word',
            name='example',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='word',
            name='image',
            field=models.ImageField(default=None, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='word',
            name='mean',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='word',
            name='synonym',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='word',
            name='word',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
