# Generated by Django 4.2.6 on 2023-10-26 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0034_alter_word_word'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='word',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
