# Generated by Django 4.2.6 on 2023-10-26 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0035_alter_word_word'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='definition',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='word',
            name='example',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='word',
            name='image',
            field=models.ImageField(default=None, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='word',
            name='level',
            field=models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], default=None, max_length=5),
        ),
        migrations.AddField(
            model_name='word',
            name='mean',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='word',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='word',
            name='synonym',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
