# Generated by Django 4.2.6 on 2023-10-26 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0037_remove_word_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='image',
            field=models.ImageField(default=None, upload_to='images/'),
        ),
    ]
