# Generated by Django 4.2.6 on 2023-10-26 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0038_word_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='spelling',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
