# Generated by Django 4.2.6 on 2023-10-27 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0039_word_spelling'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='image',
        ),
    ]
